spring:
  config:
    activate:
      on-profile: local

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        orm.jdbc.bind: trace
#        SQL: debug